### ISSUE TITLE
Github action make test

### ISSUE THREAD

**Issue by meDracula** [meDracula/.dotfiles#9]
Create a github action for testing `make test` and `build` with unit testing then finishing with `destroy` to ensure everything gets destroyed as excepted.

## Depends on
* #8 

## TODO
- [ ] Install all required dotfiles applications from rc-list.txt
- [ ] Run `make test`
- [ ] Run a `make build` then unit test and then perform a `destroy` and verify everything is destroyed.

## Time
Estimated: 01:45
Took: --:--
